---
- name: delete anonymous MySQL user
  become: yes
  mysql_user:
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    name: ""
    host_all: yes
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: remove MySQL test database
  become: yes
  mysql_db:
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
...
